### ISSUE TITLE
Setup as a GitHub action with parameters

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-heat-sensor#2]
I imagine the usage would be something like:

```yaml
    steps:
    - name: 'Heat Sensor'
      uses: jonathanpeppers/inclusive-heat-sensor@v0.1
      with:
        steps: # callers could do something custom here with an array of steps
        comment: # or just put a message for the auto-comment
```

Then initially we might try this in the .NET MAUI repo and not do anything in the steps or comment.

After, we are confident it seems ok we could make it auto-comment, or label, etc.

**Comment by rolfbjarne** [comment]
Here's an example of how I got it to work: https://github.com/rolfbjarne/sensor-tester/blob/74b0b782da53fba147b601f9a9da79004fb87f9f/.github/workflows/heat-sensor.yml#L1-L23

**Comment by jonathanpeppers** [comment]
We can close this after making a branch or tag.

**Comment by jonathanpeppers** [comment]
This is working, such as:
* https://github.com/dotnet/maui/blob/main/.github/workflows/inclusive-heat-sensor.yml

The example is:
```yaml
jobs:
  detect-heat:
    uses: jonathanpeppers/inclusive-heat-sensor/.github/workflows/comments.yml@v0.1
    secrets: inherit
```

@rolfbjarne do you know how to remove the path `.github/workflows/comments.yml`, from the place using it?
