### ISSUE TITLE
Add a feature to auto-label

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-heat-sensor#3]
This builds on #2.

Right now we just have this auto-commenting.

We could make it add a label like:
```yml
    steps:
    - name: 'Heat Sensor'
      uses: jonathanpeppers/inclusive-heat-sensor@v0.1
      with:
        label: 'heated'
```
